services:
  - type: web
    name: potato-disease-api
    env: python
    buildCommand: "pip install -r requirement.txt"
    startCommand: "uvicorn api.main:app --host 0.0.0.0 --port 10000"
    plan: free
